"""Add annual_change_type to Asset and Liability models

Revision ID: 149ec67709e9
Revises: 3645bdfa6fd5
Create Date: 2025-12-15 15:37:46.085099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149ec67709e9'
down_revision: Union[str, Sequence[str], None] = '3645bdfa6fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('annual_change_type', sa.String(), nullable=True))
    op.add_column('liabilities', sa.Column('annual_change_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liabilities', 'annual_change_type')
    op.drop_column('assets', 'annual_change_type')
    # ### end Alembic commands ###
