"""Add include_in_cash_flow to liabilities

Revision ID: 3381968f59b2
Revises: 98e071e208f1
Create Date: 2026-01-01 11:34:21.987035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3381968f59b2'
down_revision: Union[str, Sequence[str], None] = '98e071e208f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liabilities', sa.Column('include_in_cash_flow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liabilities', 'include_in_cash_flow')
    # ### end Alembic commands ###
