"""Add cell phone to UserSettings

Revision ID: 3645bdfa6fd5
Revises: 7e39f714d512
Create Date: 2025-12-15 14:57:09.657524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3645bdfa6fd5'
down_revision: Union[str, Sequence[str], None] = '7e39f714d512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('person1_birthdate', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('person1_cell_phone', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('person2_birthdate', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('person2_cell_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'person2_cell_phone')
    op.drop_column('user_settings', 'person2_birthdate')
    op.drop_column('user_settings', 'person1_cell_phone')
    op.drop_column('user_settings', 'person1_birthdate')
    # ### end Alembic commands ###
