import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcfa56a4d67'
down_revision: Union[str, Sequence[str], None] = '48e85ba03b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the new owner_id column as nullable
    op.add_column('user_settings', sa.Column('owner_id', sa.Integer(), nullable=True))

    # 2. Migrate data from user_id to owner_id
    op.execute("UPDATE user_settings SET owner_id = user_id WHERE user_id IS NOT NULL")

    # 3. Alter owner_id to be NOT NULL (now that it's populated)
    op.alter_column('user_settings', 'owner_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        # 4. Alter column types to JSONB using PostgreSQL functions for robust conversion
        # Use CASE to handle NULL or empty strings, converting them to '[]'::jsonb
        batch_op.alter_column('asset_categories',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN asset_categories IS NULL OR TRIM(asset_categories) = '' THEN '[]'::jsonb ELSE to_jsonb(string_to_array(asset_categories, ',')) END")
        batch_op.alter_column('liability_categories',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN liability_categories IS NULL OR TRIM(liability_categories) = '' THEN '[]'::jsonb ELSE to_jsonb(string_to_array(liability_categories, ',')) END")
        batch_op.alter_column('income_categories',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN income_categories IS NULL OR TRIM(income_categories) = '' THEN '[]'::jsonb ELSE to_jsonb(string_to_array(income_categories, ',')) END")
        batch_op.alter_column('expense_categories',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using="CASE WHEN expense_categories IS NULL OR TRIM(expense_categories) = '' THEN '[]'::jsonb ELSE to_jsonb(string_to_array(expense_categories, ',')) END")

        # 5. Drop and re-create constraints and foreign keys for owner_id
        batch_op.drop_constraint('user_settings_user_id_key', type_='unique') # Use the actual constraint name
        batch_op.create_unique_constraint('uq_user_settings_owner_id', ['owner_id']) # Give a name
        batch_op.drop_constraint('user_settings_user_id_fkey', type_='foreignkey') # Use the actual constraint name
        batch_op.create_foreign_key('fk_user_settings_owner_id', 'users', ['owner_id'], ['id'], ondelete='CASCADE') # Give a name
        
        # 6. Drop the old user_id column
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        # 1. Add back user_id column as nullable
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        # 2. Migrate data back (reverse of upgrade)
        batch_op.execute("UPDATE user_settings SET user_id = owner_id WHERE owner_id IS NOT NULL")
        # 3. Alter user_id to be NOT NULL
        batch_op.alter_column('user_settings', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

        # 4. Revert JSONB to VARCHAR using PostgreSQL functions
        for col_name in ['asset_categories', 'liability_categories', 'income_categories', 'expense_categories']:
            batch_op.alter_column(col_name,
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
                       existing_nullable=True,
                       postgresql_using=f"CASE WHEN {col_name} IS NULL OR {col_name} = '[]'::jsonb THEN NULL ELSE array_to_string(ARRAY(SELECT jsonb_array_elements_text({col_name})), ',') END")

        # 5. Drop and re-create constraints and foreign keys for user_id
        batch_op.drop_constraint('fk_user_settings_owner_id', type_='foreignkey')
        batch_op.create_foreign_key('user_settings_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_settings_owner_id', type_='unique')
        batch_op.create_unique_constraint('user_settings_user_id_key', ['user_id'])
        
        # 6. Drop owner_id column
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
