"""add_help_content_to_global_settings

Revision ID: 55b0b604d42b
Revises: 45079041375d
Create Date: 2026-01-01 17:53:20.139509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b0b604d42b'
down_revision: Union[str, Sequence[str], None] = '45079041375d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('help_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'help_content')
    # ### end Alembic commands ###
