"""feat: Refine asset/liability schemas and models; prepare for dynamic linking changes

Revision ID: 646dcfda0f4a
Revises: 3381968f59b2
Create Date: 2026-01-01 12:26:54.468938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646dcfda0f4a'
down_revision: Union[str, Sequence[str], None] = '3381968f59b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
