"""Add amortization fields to ProjectedAccount

Revision ID: 6f18d41e1888
Revises: 924e72fbd517
Create Date: 2026-01-01 15:25:51.895996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f18d41e1888'
down_revision: Union[str, Sequence[str], None] = '924e72fbd517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projected_accounts', sa.Column('loan_type', sa.String(), nullable=True))
    op.add_column('projected_accounts', sa.Column('principal_amount', sa.Float(), nullable=True))
    op.add_column('projected_accounts', sa.Column('interest_rate', sa.Float(), nullable=True))
    op.add_column('projected_accounts', sa.Column('loan_term_months', sa.Integer(), nullable=True))
    op.add_column('projected_accounts', sa.Column('loan_start_date', sa.String(), nullable=True))
    op.add_column('projected_accounts', sa.Column('monthly_payment', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projected_accounts', 'monthly_payment')
    op.drop_column('projected_accounts', 'loan_start_date')
    op.drop_column('projected_accounts', 'loan_term_months')
    op.drop_column('projected_accounts', 'interest_rate')
    op.drop_column('projected_accounts', 'principal_amount')
    op.drop_column('projected_accounts', 'loan_type')
    # ### end Alembic commands ###
