"""Add linked_item_id, linked_item_type, and percentage to CashFlowItem

Revision ID: 89a02fb97c1a
Revises: bd5309cd4a41
Create Date: 2025-12-19 10:55:30.056626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a02fb97c1a'
down_revision: Union[str, Sequence[str], None] = 'bd5309cd4a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow_items', sa.Column('linked_item_id', sa.Integer(), nullable=True))
    op.add_column('cashflow_items', sa.Column('linked_item_type', sa.String(), nullable=True))
    op.add_column('cashflow_items', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashflow_items', 'percentage')
    op.drop_column('cashflow_items', 'linked_item_type')
    op.drop_column('cashflow_items', 'linked_item_id')
    # ### end Alembic commands ###
