"""Refactor projection data into normalized tables

Revision ID: 924e72fbd517
Revises: a4b5b50f1bd4
Create Date: 2026-01-01 15:13:11.974123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924e72fbd517'
down_revision: Union[str, Sequence[str], None] = 'a4b5b50f1bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('initial_value', sa.Float(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['projection_id'], ['projections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projected_accounts_id'), 'projected_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_projected_accounts_name'), 'projected_accounts', ['name'], unique=False)
    op.create_table('projection_time_series_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projection_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['projected_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projection_id'], ['projections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projection_time_series_data_id'), 'projection_time_series_data', ['id'], unique=False)
    op.create_index(op.f('ix_projection_time_series_data_value_type'), 'projection_time_series_data', ['value_type'], unique=False)
    op.create_index(op.f('ix_projection_time_series_data_year'), 'projection_time_series_data', ['year'], unique=False)
    op.drop_column('projections', 'accounts_json')
    op.drop_column('projections', 'data_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projections', sa.Column('data_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projections', sa.Column('accounts_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projection_time_series_data_year'), table_name='projection_time_series_data')
    op.drop_index(op.f('ix_projection_time_series_data_value_type'), table_name='projection_time_series_data')
    op.drop_index(op.f('ix_projection_time_series_data_id'), table_name='projection_time_series_data')
    op.drop_table('projection_time_series_data')
    op.drop_index(op.f('ix_projected_accounts_name'), table_name='projected_accounts')
    op.drop_index(op.f('ix_projected_accounts_id'), table_name='projected_accounts')
    op.drop_table('projected_accounts')
    # ### end Alembic commands ###
