"""Add display_type to CustomChart model

Revision ID: bd5309cd4a41
Revises: 149ec67709e9
Create Date: 2025-12-16 08:45:22.336627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5309cd4a41'
down_revision: Union[str, Sequence[str], None] = '149ec67709e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_charts', sa.Column('display_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_charts', 'display_type')
    # ### end Alembic commands ###
