"""FORCE_SYNC_MFA

Revision ID: cfe279a86f11
Revises: 7f6d1a9c2f38
Create Date: 2026-01-28 19:55:28.734427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfe279a86f11'
down_revision: Union[str, Sequence[str], None] = '7f6d1a9c2f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'is_retirement',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_primary_authorized_email'), 'authorized_users', type_='unique')
    op.create_unique_constraint('uq_primary_authorized_user', 'authorized_users', ['primary_user_id', 'authorized_user_id'])
    op.alter_column('auto_disbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brokerages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_settings', 'free_max_projection_years',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('global_settings', 'free_max_documents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('global_settings', 'free_max_whatif_monthly',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('liabilities', 'decrease_by_principal_yearly',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('liabilities', 'create_payment_expense',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('liabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_mfa_trusted_devices_token'), table_name='mfa_trusted_devices')
    op.create_index(op.f('ix_mfa_trusted_devices_device_token_hash'), 'mfa_trusted_devices', ['device_token_hash'], unique=False)
    op.alter_column('plaid_items', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('plaid_items', 'webhook',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('plaid_items', 'error',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('plaid_items', 'available_products',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('plaid_items', 'billed_products',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('plaid_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_plaid_items_item_id'), table_name='plaid_items')
    op.drop_index(op.f('idx_plaid_items_owner_id'), table_name='plaid_items')
    op.drop_constraint(op.f('plaid_items_item_id_key'), 'plaid_items', type_='unique')
    op.create_index(op.f('ix_plaid_items_id'), 'plaid_items', ['id'], unique=False)
    op.create_index(op.f('ix_plaid_items_item_id'), 'plaid_items', ['item_id'], unique=True)
    op.drop_table_comment(
        'plaid_items',
        existing_comment='Stores Plaid access tokens and metadata for connected bank accounts',
        schema=None
    )
    op.drop_index(op.f('ix_projected_accounts_cash_flow_item_id'), table_name='projected_accounts')
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.alter_column('user_settings', 'tax_filing_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Single'::character varying"))
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'subscription_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'mfa_email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'mfa_sms_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_users_referred_by_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_referred_by_id'), 'users', ['referred_by_id'], unique=False)
    op.alter_column('users', 'mfa_sms_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'mfa_email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'subscription_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_settings', 'tax_filing_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Single'::character varying"))
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.create_index(op.f('ix_projected_accounts_cash_flow_item_id'), 'projected_accounts', ['cash_flow_item_id'], unique=False)
    op.create_table_comment(
        'plaid_items',
        'Stores Plaid access tokens and metadata for connected bank accounts',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_plaid_items_item_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_id'), table_name='plaid_items')
    op.create_unique_constraint(op.f('plaid_items_item_id_key'), 'plaid_items', ['item_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_plaid_items_owner_id'), 'plaid_items', ['owner_id'], unique=False)
    op.create_index(op.f('idx_plaid_items_item_id'), 'plaid_items', ['item_id'], unique=False)
    op.alter_column('plaid_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plaid_items', 'billed_products',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('plaid_items', 'available_products',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('plaid_items', 'error',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('plaid_items', 'webhook',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('plaid_items', 'access_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_mfa_trusted_devices_device_token_hash'), table_name='mfa_trusted_devices')
    op.create_index(op.f('ix_mfa_trusted_devices_token'), 'mfa_trusted_devices', ['device_token_hash'], unique=False)
    op.alter_column('liabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('liabilities', 'create_payment_expense',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('liabilities', 'decrease_by_principal_yearly',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('global_settings', 'free_max_whatif_monthly',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('global_settings', 'free_max_documents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('global_settings', 'free_max_projection_years',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('brokerages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auto_disbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_primary_authorized_user', 'authorized_users', type_='unique')
    op.create_unique_constraint(op.f('uq_primary_authorized_email'), 'authorized_users', ['primary_user_id', 'authorized_user_email'], postgresql_nulls_not_distinct=False)
    op.alter_column('assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('accounts', 'is_retirement',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
