"""Add projection fields to CustomChart model

Revision ID: e6d96651bbdd
Revises: 89a02fb97c1a
Create Date: 2025-12-19 15:48:43.700333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d96651bbdd'
down_revision: Union[str, Sequence[str], None] = '89a02fb97c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_charts', sa.Column('data_json', sa.String(), nullable=True))
    op.add_column('custom_charts', sa.Column('final_value', sa.Float(), nullable=True))
    op.add_column('custom_charts', sa.Column('total_contributed', sa.Float(), nullable=True))
    op.add_column('custom_charts', sa.Column('total_growth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_charts', 'total_growth')
    op.drop_column('custom_charts', 'total_contributed')
    op.drop_column('custom_charts', 'final_value')
    op.drop_column('custom_charts', 'data_json')
    # ### end Alembic commands ###
