"""feat: Add contributes_to_asset_id to CashFlowItem for asset contributions

Revision ID: f483f8aae448
Revises: 646dcfda0f4a
Create Date: 2026-01-01 12:50:51.153415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f483f8aae448'
down_revision: Union[str, Sequence[str], None] = '646dcfda0f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow_items', sa.Column('contributes_to_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cashflow_items', 'assets', ['contributes_to_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashflow_items', type_='foreignkey')
    op.drop_column('cashflow_items', 'contributes_to_asset_id')
    # ### end Alembic commands ###
