steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend Image'
    args:
      - 'build'
      - '--no-cache' # NEW: Force no-cache for frontend build
      - '-t'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$COMMIT_SHA'
      - '.'
    dir: 'ui'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend Image'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Frontend Service'
    args:
      - 'run'
      - 'deploy'
      - 'finmodel-frontend-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars=REACT_APP_API_URL=https://finmodel-backend-service-526419047208.us-east1.run.app'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '--no-cache'
      - '--pull'
      - '-t'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$COMMIT_SHA'
      - '.'
    dir: 'api'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Remove old secret env vars'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'finmodel-backend-service'
      - '--region'
      - 'us-east1'
      - '--remove-env-vars=SECRET_KEY,DB_PASSWORD,GOOGLE_CLIENT_SECRET,MAIL_PASSWORD,GOOGLE_CLIENT_ID'
    allowFailure: true

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Backend Service'
    args:
      - 'run'
      - 'deploy'
      - 'finmodel-backend-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars=DB_USER=dbadmin'
      - '--update-env-vars=DB_NAME=finmodel1'
      - '--update-env-vars=CLOUD_SQL_CONNECTION_NAME=financial-model-cloud:us-east1:finmodel-postgres-instance'
      - '--update-env-vars=MAIL_USERNAME=martin.willingham@gmail.com'
      - '--update-env-vars=MAIL_FROM=no_reply@gmail.com'
      - '--update-env-vars=MAIL_PORT=587'
      - '--update-env-vars=MAIL_SERVER=smtp.gmail.com'
      - '--update-env-vars=FRONTEND_URL=https://finmodel-frontend-service-526419047208.us-east1.run.app'
      - '--update-env-vars=PUBLIC_BACKEND_URL=https://finmodel-backend-service-526419047208.us-east1.run.app'
      - '--update-env-vars=MAIL_TLS=True'
      - '--update-env-vars=MAIL_SSL=False'
      - '--update-env-vars=USE_CREDENTIALS=True'
      - '--update-env-vars=VALIDATE_CERTS=True'
      - '--add-cloudsql-instances=financial-model-cloud:us-east1:finmodel-postgres-instance' # NEW: Enable Cloud SQL Proxy in Cloud Run
      - '--set-secrets=SECRET_KEY=_SECRET_KEY:1'
      - '--set-secrets=DB_PASSWORD=_DB_PASSWORD:1'
      - '--set-secrets=GOOGLE_CLIENT_SECRET=_GOOGLE_CLIENT_SECRET:2'
      - '--set-secrets=GOOGLE_CLIENT_ID=_GOOGLE_CLIENT_ID:2'
      - '--set-secrets=MAIL_PASSWORD=_MAIL_PASSWORD:1'
    secretEnv:
      - '_DB_PASSWORD'
      - '_GOOGLE_CLIENT_SECRET'
      - '_GOOGLE_CLIENT_ID'
      - '_MAIL_PASSWORD'
      - '_SECRET_KEY'

  - name: 'gcr.io/cloud-builders/gcloud' # Use gcloud builder which includes curl and bash
    id: 'Start Cloud SQL Proxy for Migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -sS -o /usr/local/bin/cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
        chmod +x /usr/local/bin/cloud_sql_proxy
        /usr/local/bin/cloud_sql_proxy -instances=financial-model-cloud:us-east1:finmodel-postgres-instance=tcp:0.0.0.0:5432 --port=5432 --debug &
        sleep 5 # Give proxy a moment to start
    waitFor: ['Deploy Backend Service']

  - name: 'python:3.9'
    id: 'Run Alembic Migrations'
    dir: 'api'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m pip install -r requirements.txt
        # Install netcat for checking proxy readiness
        apt-get update && apt-get install -y netcat-traditional
        
        # Wait for the Cloud SQL Proxy to be ready before running migrations
        echo "Waiting for Cloud SQL Proxy to start..."
        for i in `seq 1 10`; do
          nc -z 127.0.0.1 5432 && echo "Cloud SQL Proxy is ready!" && break
          echo "Still waiting..." && sleep 5;
        done
        # Ensure we exit if proxy didn't start
        nc -z 127.0.0.1 5432 || (echo "ERROR: Cloud SQL Proxy did not start in time." && exit 1)
        
        /usr/local/bin/alembic upgrade head
    env:
      - 'DB_USER=dbadmin'
      - 'DB_NAME=finmodel1'
      - 'DB_HOST=127.0.0.1' # Connect to the proxy running on localhost
      - 'DB_PORT=5432'     # Connect to the proxy running on port 5432
      - 'CLOUD_SQL_CONNECTION_NAME=financial-model-cloud:us-east1:finmodel-postgres-instance'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'SECRET_KEY=${_SECRET_KEY}'
    secretEnv:
      - '_DB_PASSWORD'
    waitFor: ['Start Cloud SQL Proxy for Migrations'] # Wait for the proxy to start before running migrations

options:
  # Force Cloud Build re-evaluation of secrets
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

availableSecrets:
  secretManager:
    - versionName: 'projects/financial-model-cloud/secrets/_DB_PASSWORD/versions/1'
      env: '_DB_PASSWORD'
    - versionName: 'projects/financial-model-cloud/secrets/_GOOGLE_CLIENT_SECRET/versions/2'
      env: '_GOOGLE_CLIENT_SECRET'
    - versionName: 'projects/financial-model-cloud/secrets/_GOOGLE_CLIENT_ID/versions/2'
      env: '_GOOGLE_CLIENT_ID'
    - versionName: 'projects/financial-model-cloud/secrets/_MAIL_PASSWORD/versions/1'
      env: '_MAIL_PASSWORD'
    - versionName: 'projects/financial-model-cloud/secrets/_SECRET_KEY/versions/1'
      env: '_SECRET_KEY'