steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '--no-cache'
      - '--pull'
      - '-t'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP}'
      - 'api'
      - '--build-arg'
      - 'CACHEBUSTER=${_TIMESTAMP}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker push us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP}'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Backend Service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy finmodel-backend-service \
          --image us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP} \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --project financial-model-cloud \
          --set-cloudsql-instances=financial-model-cloud:us-east1:finmodel-postgres-instance \
          --cpu=1 \
          --memory=512Mi \
          --concurrency=80 \
          --timeout=30m \
          --no-traffic

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Update Backend Traffic'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'finmodel-backend-service'
      - '--region'
      - 'us-east1'
      - '--to-latest'
      - '--project'
      - 'financial-model-cloud'
    # Temporarily removed env and secretEnv to isolate the issue

# Temporarily commented out frontend and alembic steps to simplify build process
#  - name: 'gcr.io/cloud-builders/docker'
#    id: 'Build Frontend Image'
#    args:
#      - 'build'
#      - '--no-cache'
#      - '-t'
#      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA'
#      - '--build-arg=REACT_APP_API_URL=http://localhost:8000' # Placeholder URL
#      - '.'
#    dir: 'ui'
#    waitFor: ['Deploy Backend Service']

#  - name: 'gcr.io/cloud-builders/docker'
#    id: 'Push Frontend Image'
#    args:
#      - 'push'
#      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA'
#    waitFor: ['Build Frontend Image']

#  - name: 'gcr.io/cloud-builders/gcloud'
#    id: 'Deploy Frontend Service'
#    args:
#      - 'run'
#      - 'deploy'
#      - 'finmodel-frontend-service'
#      - '--image'
#      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA'
#      - '--region'
#      - 'us-east1'
#      - '--platform'
#      - 'managed'
#      - '--allow-unauthenticated'
#      - '--project'
#      - 'financial-model-cloud'
#    waitFor: ['Push Frontend Image']

#  - name: 'python:3.11'
#    id: 'Run Alembic Migrations'
#    dir: 'api'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        python3 -m pip install -r requirements.txt
#        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.20.0/cloud-sql-proxy.linux.amd64
#        chmod +x cloud-sql-proxy
#        mkdir -p /cloudsql
#        ./cloud-sql-proxy financial-model-cloud:us-east1:finmodel-postgres-instance --unix-socket /cloudsql &
#        
#        echo "Waiting for Cloud SQL Proxy to start..." && for i in $(seq 1 10); do if [ -S /cloudsql/financial-model-cloud:us-east1:finmodel-postgres-instance/.s.PGSQL.5432 ]; then echo "Cloud SQL Proxy is ready!"; break; fi; echo "Still waiting..." && sleep 10; done && if ! [ -S /cloudsql/financial-model-cloud:us-east1:finmodel-postgres-instance/.s.PGSQL.5432 ]; then echo "ERROR: Cloud SQL Proxy did not start in time." && exit 1; fi
#        (/usr/local/bin/alembic current > /dev/null 2>&1 || /usr/local/bin/alembic stamp base) && /usr/local/bin/alembic upgrade head
#    env:
#      - 'DB_USER=dbadmin'
#      - 'DB_NAME=finmodel1'
#      - 'CLOUD_SQL_CONNECTION_NAME=financial-model-cloud:us-east1:finmodel-postgres-instance'
#    timeout: 1800s
#    secretEnv:
#      - '_DB_PASSWORD' 

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

# Temporarily removed availableSecrets section to simplify build process

substitutions:
  _TIMESTAMP: $(date +%s)
  _COMMIT_SHA: $(git rev-parse HEAD)
