steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '--no-cache'
      - '--pull'
      - '-t'
      - 'us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP}'
      - 'api'
      - '--build-arg'
      - 'CACHEBUSTER=${_TIMESTAMP}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker push us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP}'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy & Configure Services'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e # Exit immediately if a command exits with a non-zero status.

        echo "--- Removing old secret env vars from backend service ---"
        gcloud run services update finmodel-backend-service \
          --region us-east1 \
          --project financial-model-cloud \
          --remove-env-vars=SECRET_KEY,DB_PASSWORD,GOOGLE_CLIENT_SECRET,MAIL_PASSWORD,GOOGLE_CLIENT_ID \
          || true # Allow failure if no old vars exist

        echo "--- Deploying Backend Service (initial) ---"
        gcloud run deploy finmodel-backend-service \
          --image us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-backend:$_COMMIT_SHA-${_TIMESTAMP} \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --project financial-model-cloud \
          --no-traffic \
          --update-env-vars=DB_USER=dbadmin,DB_NAME=finmodel1,CLOUD_SQL_CONNECTION_NAME=financial-model-cloud:us-east1:finmodel-postgres-instance \
          --update-env-vars=MAIL_USERNAME=martin.willingham@gmail.com,MAIL_FROM=no_reply@gmail.com,MAIL_PORT=587,MAIL_SERVER=smtp.gmail.com \
          --update-env-vars=MAIL_TLS=True,MAIL_SSL=False,USE_CREDENTIALS=True,VALIDATE_CERTS=True \
          --add-cloudsql-instances=financial-model-cloud:us-east1:finmodel-postgres-instance \
          --set-secrets=SECRET_KEY=_SECRET_KEY:1,DB_PASSWORD=_DB_PASSWORD:1,GOOGLE_CLIENT_SECRET=_GOOGLE_CLIENT_SECRET:2,GOOGLE_CLIENT_ID=_GOOGLE_CLIENT_ID:2,MAIL_PASSWORD=_MAIL_PASSWORD:1

        echo "--- Getting Backend Service URL ---"
        BACKEND_URL=$(gcloud run services describe finmodel-backend-service --region us-east1 --project financial-model-cloud --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        
        echo "--- Building Frontend Image using dynamic Backend URL ---"
        (cd ui && docker build --no-cache -t us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA --build-arg=REACT_APP_API_URL=\$BACKEND_URL .)
        
        echo "--- Pushing Frontend Image ---"
        docker push us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA

        echo "--- Deploying Frontend Service (initial) ---"
        gcloud run deploy finmodel-frontend-service \
          --image us-east1-docker.pkg.dev/financial-model-cloud/finmodel-repo/finmodel-frontend:$_COMMIT_SHA \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --project financial-model-cloud

        echo "--- Getting Frontend Service URL ---"
        FRONTEND_URL=$(gcloud run services describe finmodel-frontend-service --region us-east1 --project financial-model-cloud --format='value(status.url)')
        echo "Frontend URL: $FRONTEND_URL"

        echo "--- Updating Backend Service with Frontend URL ---"
        gcloud run services update finmodel-backend-service \
          --region us-east1 \
          --project financial-model-cloud \
          --update-env-vars=PUBLIC_BACKEND_URL=\$BACKEND_URL,FRONTEND_URL=\$FRONTEND_URL
        
        echo "--- Updating Frontend Service with Backend URL ---"
        gcloud run services update finmodel-frontend-service \
          --region us-east1 \
          --project financial-model-cloud \
          --update-env-vars=REACT_APP_API_URL=\$BACKEND_URL

    secretEnv:
      - '_DB_PASSWORD'
      - '_GOOGLE_CLIENT_SECRET'
      - '_GOOGLE_CLIENT_ID'
      - '_MAIL_PASSWORD'
      - '_SECRET_KEY'
    waitFor: ['Push Backend Image']

  - name: 'python:3.11'
    id: 'Run Alembic Migrations'
    dir: 'api'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Installing Python requirements for Alembic ---"
        python3 -m pip install -r requirements.txt

        echo "--- Downloading Cloud SQL Proxy ---"
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.20.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

        echo "--- Starting Cloud SQL Proxy ---"
        mkdir -p /cloudsql
        ./cloud-sql-proxy financial-model-cloud:us-east1:finmodel-postgres-instance --unix-socket /cloudsql &
        
        echo "--- Waiting for Cloud SQL Proxy to start ---"
        for i in $(seq 1 10); do 
          if [ -S /cloudsql/financial-model-cloud:us-east1:finmodel-postgres-instance/.s.PGSQL.5432 ]; then 
            echo "Cloud SQL Proxy is ready!"; 
            break; 
          fi; 
          echo "Still waiting..." && sleep 10; 
        done
        if ! [ -S /cloudsql/financial-model-cloud:us-east1:finmodel-postgres-instance/.s.PGSQL.5432 ]; then 
          echo "ERROR: Cloud SQL Proxy did not start in time." && exit 1; 
        fi

        echo "--- Running Alembic Migrations ---"
        (/usr/local/bin/alembic current > /dev/null 2>&1 || /usr/local/bin/alembic stamp base) && /usr/local/bin/alembic upgrade head
    env:
      - 'DB_USER=dbadmin'
      - 'DB_NAME=finmodel1'
      - 'DB_HOST=/cloudsql/financial-model-cloud:us-east1:finmodel-postgres-instance'
      - 'CLOUD_SQL_CONNECTION_NAME=financial-model-cloud:us-east1:finmodel-postgres-instance'
    timeout: 1800s
    secretEnv:
      - '_DB_PASSWORD' 

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

availableSecrets:
  secretManager:
    - versionName: 'projects/financial-model-cloud/secrets/_DB_PASSWORD/versions/1'
      env: '_DB_PASSWORD'
    - versionName: 'projects/financial-model-cloud/secrets/_GOOGLE_CLIENT_SECRET/versions/2'
      env: '_GOOGLE_CLIENT_SECRET'
    - versionName: 'projects/financial-model-cloud/secrets/_GOOGLE_CLIENT_ID/versions/2'
      env: '_GOOGLE_CLIENT_ID'
    - versionName: 'projects/financial-model-cloud/secrets/_MAIL_PASSWORD/versions/1'
      env: '_MAIL_PASSWORD'
    - versionName: 'projects/financial-model-cloud/secrets/_SECRET_KEY/versions/1'
      env: '_SECRET_KEY'
substitutions:
  _TIMESTAMP: $(date +%s)
